# Generated by Django 5.1.7 on 2025-10-02 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_id',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='la description doit contenir au moins 30 caractères')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
