# Generated by Django 5.1.7 on 2025-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_alter_conference_conference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
