# Generated by Django 5.1.7 on 2025-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0004_alter_submission_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
