# Generated by Django 5.1.7 on 2025-10-23 12:05

import ConferenceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0005_alter_conference_conference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=100, validators=[ConferenceApp.models.Conference.name_conference]),
        ),
    ]
