# Generated by Django 5.1.7 on 2025-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0006_alter_conference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
